sudo: required
language: node_js

node_js:
  - "node"

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

script:
  - npm run test -- --watch=false
  - npm run e2e

after_success:
  - if ["$TRAVIS_BRANCH" == "master"]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    export REPO=wizofgoz/evecommander-web;
    docker build -t $REPO:$COMMIT .;
    docker tag $REPO:$COMMIT $REPO:latest;
    docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER;
    docker push $REPO;
    fi
